version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: test_project
    command: ["/test_project/docker/app.sh"]
    ports:
      - 8888:8000
    depends_on:
      - db


#
#  redis:
#    image: redis:7
#    container_name: redis
#    command: --port 5370
#    expose:
#      - 5370
#    env_file:
#      - ../TestsProject/.env-non-dev

#  celery:
#    build:
#      context: .
#    env_file:
#      - .env-non-dev
#    container_name: celery_app
#    command: ["/fastapi_app/docker/celery.sh", "celery"]
#    depends_on:
#      - redis
#
#  flower:
#    build:
#      context: .
#    env_file:
#      - .env-non-dev
#    container_name: flower_app
#    command: ["/fastapi_app/docker/celery.sh", "flower"]
#    depends_on:
#      - redis
#      - celery
#    ports:
#      - 8888:5555